# Generated by Django 5.0.3 on 2024-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.IntegerField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=50)),
                ("Date", models.DateField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
